<?php

declare(strict_types=1);


/* ========================================
   SECURE SESSION SETTINGS
======================================== */

if (session_status() === PHP_SESSION_NONE) {

    $isHttps =
        (
            !empty($_SERVER["HTTPS"]) &&
            strtolower((string)$_SERVER["HTTPS"]) !== "off"
        )
        ||
        (
            isset($_SERVER["SERVER_PORT"]) &&
            (int)$_SERVER["SERVER_PORT"] === 443
        );

    /*
     * Prevent PHP from accepting attacker-supplied
     * session IDs that were not generated by PHP.
     */
    ini_set(
        "session.use_strict_mode",
        "1"
    );

    ini_set(
        "session.use_only_cookies",
        "1"
    );

    ini_set(
        "session.cookie_httponly",
        "1"
    );

    session_name("BRGC_SESSION");

    session_set_cookie_params([
        "lifetime" => 0,
        "path" => "/",
        "domain" => "",
        "secure" => $isHttps,
        "httponly" => true,
        "samesite" => "Lax"
    ]);

    session_start();
}


/* ========================================
   CSRF TOKEN
======================================== */

function csrfToken(): string
{
    if (
        !isset($_SESSION["csrf_token"]) ||
        !is_string($_SESSION["csrf_token"]) ||
        $_SESSION["csrf_token"] === ""
    ) {
        $_SESSION["csrf_token"] =
            bin2hex(random_bytes(32));
    }

    return $_SESSION["csrf_token"];
}


/* ========================================
   VERIFY CSRF TOKEN
======================================== */

function verifyCsrfToken(?string $token): bool
{
    if (
        $token === null ||
        !isset($_SESSION["csrf_token"]) ||
        !is_string($_SESSION["csrf_token"]) ||
        $_SESSION["csrf_token"] === ""
    ) {
        return false;
    }

    return hash_equals(
        $_SESSION["csrf_token"],
        $token
    );
}


/* ========================================
   LOGIN PAGE PATH
======================================== */

function loginPath(): string
{
    $scriptName =
        (string)($_SERVER["SCRIPT_NAME"] ?? "");

    /*
     * Protected pages inside /admin/
     * need ../login.php.
     *
     * Customer/root pages use login.php.
     */
    if (
        strpos(
            str_replace("\\", "/", $scriptName),
            "/admin/"
        ) !== false
    ) {
        return "../login.php";
    }

    return "login.php";
}


/* ========================================
   REDIRECT TO UNIFIED LOGIN
======================================== */

function redirectToLogin(): never
{
    header(
        "Location: " . loginPath()
    );

    exit;
}


/* ========================================
   GET CURRENT USER FROM DATABASE
======================================== */

function getAuthenticatedUser(): ?array
{
    global $conn;

    if (
        !isset($_SESSION["user_id"]) ||
        !is_numeric($_SESSION["user_id"])
    ) {
        return null;
    }

    $userId =
        filter_var(
            $_SESSION["user_id"],
            FILTER_VALIDATE_INT
        );

    if (
        $userId === false ||
        $userId <= 0
    ) {
        return null;
    }

    if (
        !isset($conn) ||
        !($conn instanceof PDO)
    ) {
        return null;
    }

    $stmt = $conn->prepare("
        SELECT
            id,
            name,
            first_name,
            middle_name,
            last_name,
            email,
            birthdate,
            phone,
            role,
            created_at
        FROM users
        WHERE id = ?
        LIMIT 1
    ");

    $stmt->execute([
        $userId
    ]);

    $user =
        $stmt->fetch(PDO::FETCH_ASSOC);

    if (!$user) {
        return null;
    }

    $role =
        (string)($user["role"] ?? "");

    if (
        $role !== "admin" &&
        $role !== "customer"
    ) {
        return null;
    }

    return $user;
}


/* ========================================
   CHECK IF USER IS LOGGED IN
======================================== */

function isLoggedIn(): bool
{
    return getAuthenticatedUser() !== null;
}


/* ========================================
   CURRENT USER ID
======================================== */

function currentUserId(): ?int
{
    $user =
        getAuthenticatedUser();

    if (!$user) {
        return null;
    }

    return (int)$user["id"];
}


/* ========================================
   CURRENT USER
======================================== */

function currentUser(): ?array
{
    return getAuthenticatedUser();
}


/* ========================================
   CURRENT USER ROLE
======================================== */

function currentUserRole(): ?string
{
    $user =
        getAuthenticatedUser();

    if (!$user) {
        return null;
    }

    return (string)$user["role"];
}


/* ========================================
   REQUIRE LOGIN
======================================== */

function requireLogin(): void
{
    if (!isLoggedIn()) {

        /*
         * Clear invalid session information
         * before sending the user back to login.
         */
        unset(
            $_SESSION["user_id"],
            $_SESSION["user_name"],
            $_SESSION["user_email"],
            $_SESSION["user_phone"],
            $_SESSION["user_role"]
        );

        redirectToLogin();
    }
}


/* ========================================
   REQUIRE ADMIN
======================================== */

function requireAdmin(): void
{
    requireLogin();

    if (currentUserRole() !== "admin") {

        http_response_code(403);

        exit("Access denied.");
    }
}


/* ========================================
   REQUIRE CUSTOMER
======================================== */

function requireCustomer(): void
{
    requireLogin();

    if (currentUserRole() !== "customer") {

        http_response_code(403);

        exit("Access denied.");
    }
}


/* ========================================
   STORE AUTHENTICATED USER SESSION
======================================== */

function loginUser(array $user): void
{
    $role =
        (string)($user["role"] ?? "");

    if (
        $role !== "admin" &&
        $role !== "customer"
    ) {
        throw new RuntimeException(
            "Invalid account role."
        );
    }

    /*
     * Prevent session fixation.
     */
    session_regenerate_id(true);

    $_SESSION["user_id"] =
        (int)$user["id"];

    $_SESSION["user_name"] =
        (string)$user["name"];

    $_SESSION["user_email"] =
        (string)$user["email"];

    $_SESSION["user_phone"] =
        (string)($user["phone"] ?? "");

    $_SESSION["user_role"] =
        $role;

    /*
     * Generate a fresh CSRF token
     * after authentication.
     */
    $_SESSION["csrf_token"] =
        bin2hex(random_bytes(32));

    /*
     * Store session creation time.
     */
    $_SESSION["authenticated_at"] =
        time();

    /*
     * Optional inactivity timestamp.
     */
    $_SESSION["last_activity"] =
        time();
}


/* ========================================
   LOGOUT USER
======================================== */

function logoutUser(): never
{
    $_SESSION = [];

    if (
        ini_get("session.use_cookies")
    ) {

        $params =
            session_get_cookie_params();

        setcookie(
            session_name(),
            "",
            [
                "expires" =>
                    time() - 42000,

                "path" =>
                    $params["path"] ?? "/",

                "domain" =>
                    $params["domain"] ?? "",

                "secure" =>
                    (bool)($params["secure"] ?? false),

                "httponly" =>
                    (bool)($params["httponly"] ?? true),

                "samesite" =>
                    $params["samesite"] ?? "Lax"
            ]
        );
    }

    session_destroy();

    redirectToLogin();
}


/* ========================================
   LOGIN RATE LIMIT TABLE
======================================== */

function ensureLoginRateLimitTable(): void
{
    global $conn;

    static $ready = false;

    if ($ready) {
        return;
    }

    if (
        !isset($conn) ||
        !($conn instanceof PDO)
    ) {
        throw new RuntimeException(
            "Database connection unavailable."
        );
    }

    $conn->exec("
        CREATE TABLE IF NOT EXISTS login_attempts (
            id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            identifier VARCHAR(191) NOT NULL,
            ip_address VARCHAR(45) NOT NULL,
            failed_attempts INT UNSIGNED NOT NULL DEFAULT 0,
            first_failed_at DATETIME DEFAULT NULL,
            last_attempt_at DATETIME DEFAULT NULL,
            locked_until DATETIME DEFAULT NULL,
            UNIQUE KEY unique_identifier_ip
                (identifier, ip_address),
            INDEX idx_ip_address (ip_address),
            INDEX idx_locked_until (locked_until)
        )
        ENGINE=InnoDB
        DEFAULT CHARSET=utf8mb4
        COLLATE=utf8mb4_unicode_ci
    ");

    $ready = true;
}


/* ========================================
   CLIENT IP
======================================== */

function clientIpAddress(): string
{
    /*
     * Do not blindly trust X-Forwarded-For.
     * REMOTE_ADDR is appropriate for a normal
     * local XAMPP installation.
     */
    $ip =
        (string)(
            $_SERVER["REMOTE_ADDR"]
            ?? "0.0.0.0"
        );

    if (
        filter_var(
            $ip,
            FILTER_VALIDATE_IP
        ) === false
    ) {
        return "0.0.0.0";
    }

    return $ip;
}


/* ========================================
   CHECK RATE LIMIT
======================================== */

function loginRateLimitExceeded(
    string $identifier
): bool {

    global $conn;

    ensureLoginRateLimitTable();

    $ip =
        clientIpAddress();

    $stmt = $conn->prepare("
        SELECT
            locked_until
        FROM login_attempts
        WHERE identifier = ?
          AND ip_address = ?
        LIMIT 1
    ");

    $stmt->execute([
        $identifier,
        $ip
    ]);

    $row =
        $stmt->fetch(PDO::FETCH_ASSOC);

    if (!$row) {
        return false;
    }

    if (
        empty($row["locked_until"])
    ) {
        return false;
    }

    $lockedUntil =
        strtotime(
            (string)$row["locked_until"]
        );

    return
        $lockedUntil !== false &&
        time() < $lockedUntil;
}


/* ========================================
   REGISTER FAILED LOGIN
======================================== */

function registerFailedLogin(
    string $identifier
): void {

    global $conn;

    ensureLoginRateLimitTable();

    $ip =
        clientIpAddress();

    $now =
        date("Y-m-d H:i:s");

    /*
     * Account + IP bucket.
     *
     * 5 failures -> 5 minute lock.
     */
    $select = $conn->prepare("
        SELECT
            id,
            failed_attempts,
            first_failed_at,
            locked_until
        FROM login_attempts
        WHERE identifier = ?
          AND ip_address = ?
        LIMIT 1
    ");

    $select->execute([
        $identifier,
        $ip
    ]);

    $row =
        $select->fetch(PDO::FETCH_ASSOC);

    if (!$row) {

        $insert = $conn->prepare("
            INSERT INTO login_attempts
            (
                identifier,
                ip_address,
                failed_attempts,
                first_failed_at,
                last_attempt_at,
                locked_until
            )
            VALUES
            (?, ?, 1, ?, ?, NULL)
        ");

        $insert->execute([
            $identifier,
            $ip,
            $now,
            $now
        ]);

        return;
    }

    $attempts =
        (int)$row["failed_attempts"];

    $firstFailed =
        $row["first_failed_at"]
            ? strtotime(
                (string)$row["first_failed_at"]
            )
            : false;

    /*
     * Reset stale attempts after 15 minutes.
     */
    if (
        $firstFailed === false ||
        time() - $firstFailed > 900
    ) {

        $update = $conn->prepare("
            UPDATE login_attempts
            SET
                failed_attempts = 1,
                first_failed_at = ?,
                last_attempt_at = ?,
                locked_until = NULL
            WHERE id = ?
        ");

        $update->execute([
            $now,
            $now,
            (int)$row["id"]
        ]);

        return;
    }

    $attempts++;

    $lockedUntil = null;

    if ($attempts >= 5) {

        $lockedUntil =
            date(
                "Y-m-d H:i:s",
                time() + 300
            );
    }

    $update = $conn->prepare("
        UPDATE login_attempts
        SET
            failed_attempts = ?,
            last_attempt_at = ?,
            locked_until = ?
        WHERE id = ?
    ");

    $update->execute([
        $attempts,
        $now,
        $lockedUntil,
        (int)$row["id"]
    ]);
}


/* ========================================
   CLEAR FAILED LOGIN RECORD
======================================== */

function clearFailedLogin(
    string $identifier
): void {

    global $conn;

    ensureLoginRateLimitTable();

    $ip =
        clientIpAddress();

    $stmt = $conn->prepare("
        DELETE FROM login_attempts
        WHERE identifier = ?
          AND ip_address = ?
    ");

    $stmt->execute([
        $identifier,
        $ip
    ]);
}
?>